import bpy
import uuid

baker = bpy.context.scene.qbaker
baker.maps.clear()

# Base
item_sub_1 = baker.maps.add()
item_sub_1.name = uuid.uuid4().hex[:8]
item_sub_1.label = "Base"
item_sub_1.use_include = True
item_sub_1.type = "BASE_COLOR"
item_sub_1.base_color.name = ""
item_sub_1.base_color.suffix = "Base"
item_sub_1.base_color.samples = 1
item_sub_1.base_color.use_alpha = True
item_sub_1.base_color.denoise = False
item_sub_1.base_color.custom = False
item_sub_1.base_color.bake.name = ""
item_sub_1.base_color.bake.size = "1024"
item_sub_1.base_color.bake.format = "PNG"
item_sub_1.base_color.bake.color_depth = "8"
item_sub_1.base_color.bake.color_depth_exr = "32"
item_sub_1.base_color.bake.compression = 15
item_sub_1.base_color.bake.quality = 90
item_sub_1.base_color.bake.exr_codec = "ZIP"
item_sub_1.base_color.bake.tiff_codec = "DEFLATE"
item_sub_1.base_color.image = None

# Mask
item_sub_1 = baker.maps.add()
item_sub_1.name = uuid.uuid4().hex[:8]
item_sub_1.label = "Mask"
item_sub_1.use_include = True
item_sub_1.type = "CHANNEL_PACK"
item_sub_1.channel_pack.name = "Channel Pack"
item_sub_1.channel_pack.suffix = "Mask"
item_sub_1.channel_pack.mode = "RGBA"
item_sub_1.channel_pack.r_channel = "METALLIC"
item_sub_1.channel_pack.g_channel = "OCCLUSION"
item_sub_1.channel_pack.b_channel = "NONE"
item_sub_1.channel_pack.rgb_channel = "BASE_COLOR"
item_sub_1.channel_pack.a_channel = "GLOSSINESS"
item_sub_1.channel_pack.glossiness.name = ""
item_sub_1.channel_pack.glossiness.image = None
item_sub_1.channel_pack.glossiness.samples = 1
item_sub_1.channel_pack.glossiness.denoise = False
item_sub_1.channel_pack.glossiness.custom = False
item_sub_1.channel_pack.glossiness.bake.name = ""
item_sub_1.channel_pack.glossiness.bake.size = "1024"
item_sub_1.channel_pack.glossiness.bake.format = "PNG"
item_sub_1.channel_pack.glossiness.bake.color_depth = "8"
item_sub_1.channel_pack.glossiness.bake.color_depth_exr = "32"
item_sub_1.channel_pack.glossiness.bake.compression = 15
item_sub_1.channel_pack.glossiness.bake.quality = 90
item_sub_1.channel_pack.glossiness.bake.exr_codec = "ZIP"
item_sub_1.channel_pack.glossiness.bake.tiff_codec = "DEFLATE"
item_sub_1.channel_pack.glossiness.suffix = "Glossiness"
item_sub_1.channel_pack.metallic.name = ""
item_sub_1.channel_pack.metallic.image = None
item_sub_1.channel_pack.metallic.samples = 1
item_sub_1.channel_pack.metallic.denoise = False
item_sub_1.channel_pack.metallic.custom = False
item_sub_1.channel_pack.metallic.bake.name = ""
item_sub_1.channel_pack.metallic.bake.size = "1024"
item_sub_1.channel_pack.metallic.bake.format = "PNG"
item_sub_1.channel_pack.metallic.bake.color_depth = "8"
item_sub_1.channel_pack.metallic.bake.color_depth_exr = "32"
item_sub_1.channel_pack.metallic.bake.compression = 15
item_sub_1.channel_pack.metallic.bake.quality = 90
item_sub_1.channel_pack.metallic.bake.exr_codec = "ZIP"
item_sub_1.channel_pack.metallic.bake.tiff_codec = "DEFLATE"
item_sub_1.channel_pack.metallic.suffix = "Metallic"
item_sub_1.channel_pack.occlusion.name = ""
item_sub_1.channel_pack.occlusion.image = None
item_sub_1.channel_pack.occlusion.use_preview = False
item_sub_1.channel_pack.occlusion.suffix = "Occlusion"
item_sub_1.channel_pack.occlusion.samples = 10
item_sub_1.channel_pack.occlusion.distance = 0.5
item_sub_1.channel_pack.occlusion.only_local = True
item_sub_1.channel_pack.occlusion.invert_ao = False
item_sub_1.channel_pack.occlusion.denoise = False
item_sub_1.channel_pack.occlusion.custom = False
item_sub_1.channel_pack.occlusion.bake.name = ""
item_sub_1.channel_pack.occlusion.bake.size = "1024"
item_sub_1.channel_pack.occlusion.bake.format = "PNG"
item_sub_1.channel_pack.occlusion.bake.color_depth = "8"
item_sub_1.channel_pack.occlusion.bake.color_depth_exr = "32"
item_sub_1.channel_pack.occlusion.bake.compression = 15
item_sub_1.channel_pack.occlusion.bake.quality = 90
item_sub_1.channel_pack.occlusion.bake.exr_codec = "ZIP"
item_sub_1.channel_pack.occlusion.bake.tiff_codec = "DEFLATE"

# Normal
item_sub_1 = baker.maps.add()
item_sub_1.name = uuid.uuid4().hex[:8]
item_sub_1.label = "Normal"
item_sub_1.use_include = True
item_sub_1.type = "NORMAL"
item_sub_1.normal.name = "Normal"
item_sub_1.normal.image = None
item_sub_1.normal.suffix = "Normal"
item_sub_1.normal.space = "TANGENT"
item_sub_1.normal.type = "OPENGL"
item_sub_1.normal.r = "POS_X"
item_sub_1.normal.g = "POS_X"
item_sub_1.normal.b = "POS_X"
item_sub_1.normal.samples = 1
item_sub_1.normal.denoise = False
item_sub_1.normal.custom = False
item_sub_1.normal.bake.name = ""
item_sub_1.normal.bake.size = "1024"
item_sub_1.normal.bake.format = "PNG"
item_sub_1.normal.bake.color_depth = "8"
item_sub_1.normal.bake.color_depth_exr = "32"
item_sub_1.normal.bake.compression = 15
item_sub_1.normal.bake.quality = 90
item_sub_1.normal.bake.exr_codec = "ZIP"
item_sub_1.normal.bake.tiff_codec = "DEFLATE"

# Coat
item_sub_1 = baker.maps.add()
item_sub_1.name = uuid.uuid4().hex[:8]
item_sub_1.label = "Coat"
item_sub_1.use_include = True
if bpy.app.version >= (4, 0, 0):
    item_sub_1.type = "COAT_WEIGHT"
    item_sub_1.coat_weight.name = ""
    item_sub_1.coat_weight.image = None
    item_sub_1.coat_weight.samples = 1
    item_sub_1.coat_weight.denoise = False
    item_sub_1.coat_weight.custom = False
    item_sub_1.coat_weight.bake.name = ""
    item_sub_1.coat_weight.bake.size = "1024"
    item_sub_1.coat_weight.bake.format = "PNG"
    item_sub_1.coat_weight.bake.color_depth = "8"
    item_sub_1.coat_weight.bake.color_depth_exr = "32"
    item_sub_1.coat_weight.bake.compression = 15
    item_sub_1.coat_weight.bake.quality = 90
    item_sub_1.coat_weight.bake.exr_codec = "ZIP"
    item_sub_1.coat_weight.bake.tiff_codec = "DEFLATE"
    item_sub_1.coat_weight.suffix = "Coat"
else:
    item_sub_1.type = "CLEARCOAT"
    item_sub_1.clearcoat.name = ""
    item_sub_1.clearcoat.image = None
    item_sub_1.clearcoat.samples = 1
    item_sub_1.clearcoat.denoise = False
    item_sub_1.clearcoat.custom = False
    item_sub_1.clearcoat.bake.name = ""
    item_sub_1.clearcoat.bake.size = "1024"
    item_sub_1.clearcoat.bake.format = "PNG"
    item_sub_1.clearcoat.bake.color_depth = "8"
    item_sub_1.clearcoat.bake.color_depth_exr = "32"
    item_sub_1.clearcoat.bake.compression = 15
    item_sub_1.clearcoat.bake.quality = 90
    item_sub_1.clearcoat.bake.exr_codec = "ZIP"
    item_sub_1.clearcoat.bake.tiff_codec = "DEFLATE"
    item_sub_1.clearcoat.suffix = "Coat"

# Emission
item_sub_1 = baker.maps.add()
baker.active_map_index = len(baker.maps) - 1
item_sub_1.name = uuid.uuid4().hex[:8]
item_sub_1.label = "Emission"
item_sub_1.use_include = True
item_sub_1.type = "EMISSION"
item_sub_1.emission.name = "Emission"
item_sub_1.emission.image = None
item_sub_1.emission.samples = 1
item_sub_1.emission.denoise = False
item_sub_1.emission.custom = False
item_sub_1.emission.bake.name = ""
item_sub_1.emission.bake.size = "1024"
item_sub_1.emission.bake.format = "PNG"
item_sub_1.emission.bake.color_depth = "8"
item_sub_1.emission.bake.color_depth_exr = "32"
item_sub_1.emission.bake.compression = 15
item_sub_1.emission.bake.quality = 90
item_sub_1.emission.bake.exr_codec = "ZIP"
item_sub_1.emission.bake.tiff_codec = "DEFLATE"
item_sub_1.emission.suffix = "Emission"
